logging:
  level:
    org.springframework: info
    com.order.product: debug
server:
  port: 19113
  error:
    include-message: always

info:
  application:
    name: ${spring.application.name}

spring:
  main:
    banner-mode: "off"
  jackson:
    default-property-inclusion: non_null