spring:
  datasource:
    url:  jdbc:postgresql://localhost:5438/
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect